//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
<<<<<<< HEAD
<<<<<<< HEAD
//     Runtime Version:4.0.30319.42000
=======
//     Runtime Version:4.0.30319.34209
>>>>>>> ca67c7307c2ccda21554de9fb2824b3e5eb9a0d9
=======
//     Runtime Version:4.0.30319.34209
>>>>>>> ca67c7307c2ccda21554de9fb2824b3e5eb9a0d9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD
<<<<<<< HEAD
namespace Latihan_2_1_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
=======
=======
>>>>>>> ca67c7307c2ccda21554de9fb2824b3e5eb9a0d9
namespace Latihan_2_1_Final_.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
<<<<<<< HEAD
>>>>>>> ca67c7307c2ccda21554de9fb2824b3e5eb9a0d9
=======
>>>>>>> ca67c7307c2ccda21554de9fb2824b3e5eb9a0d9
                return defaultInstance;
            }
        }
    }
}
